baseURL = 'https://christiaanbloo.com/'
languageCode = 'en'
title = 'Christiaan Bloo'
removePathAccents = true
pluralizelisttitles = false
timeout = '60s'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false

[menu]
[[menu.main]]
  name = 'About'
  pageRef = '/about'
  weight = 1
[[menu.main]]
  name = 'Contact'
  pageRef = '/contact'
  weight = 2
[[menu.main]]
  name = 'Resume'
  pageRef = '/resume'
  weight = 3
[[menu.main]]
  name = 'Music'
  pageRef = '/music'
  weight = 4
[[menu.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 5


[params]
  [params.site]
    description = "TODO"

[outputs]
  taxonomy = ['HTML']
  home = ['HTML']
  section = ['HTML']
  page = ['HTML']
